[build-system]

requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"


# Files to include in source distributions
[tool.flit.sdist]

# README.md, LICENSE.txt, pyproject.toml, .gitignore, and src are automatically included
include = ["example.png", "example_default_style.png", "example_thin.png", "generate_example.py", "requirements.txt"]


[project]

name = "winflame"
dynamic = ["version", "description"]
keywords = ["storage", "file", "space", "tree", "flame", "graph", "distribution", "windows", "command", "command-line",
    "command line", "cli"]

readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE.txt"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
#    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)", # License classifiers are deprecated
    "Natural Language :: English",
    "Environment :: Console",
    "Operating System :: Microsoft :: Windows",
    "Typing :: Typed",

    "Topic :: Utilities",
    "Topic :: System",
    "Topic :: System :: Filesystems",

    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",

    "Programming Language :: Python",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

# Dependencies are mirrored in requirements.txt
dependencies = [
    "pywin32 >= 312", # "[The `~=` operator] MUST NOT be used with a single segment version number such as `~=1`." Source: https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release
    "pillow ~= 12.3.0",
]
requires-python = ">= 3.10"


[project.urls]

github = "https://github.com/the-can-of-soup/winflame"
repository = "https://github.com/the-can-of-soup/winflame.git"
issues = "https://github.com/the-can-of-soup/winflame/issues"


# Terminal command configuration
[project.scripts]

winflame = "winflame.cli:cli"


# `pipx run` configuration
[project.entry-points."pipx.run"]

winflame = "winflame.cli:cli"
